@startuml 自販機クラス図
class 自動販売機{}
class ボタン1{}
class ボタン2{}
class ボタン3{}
class ボタン4{}
class ボタン5{}
class ボタン6{}
class ボタン7{}
class ボタン8{}
class ボタン9{}
class ボタン10{}
class 料金装置{}
class ベンダー装置{}
自動販売機 o-- ボタン1
自動販売機 o-- ボタン2
自動販売機 o-- ボタン3
自動販売機 o-- ボタン4
自動販売機 o-- ボタン5
自動販売機 o-- ボタン6
自動販売機 o-- ボタン7
自動販売機 o-- ボタン8
自動販売機 o-- ボタン9
自動販売機 o-- ボタン10
自動販売機 o-- 料金装置
自動販売機 o-- ベンダー装置
@enduml


