@startuml ライントレーサー 
actor ユーザー as User
actor 光センサー as Sensor

rectangle ライントレーサー {
User --> (電源SWを入れる)
(電源SWを入れる) --> (システム起動)
(システム起動) --> (光センサーが黒いライン上にあるか判定)
Sensor --> (光センサーが黒いライン上にあるか判定)
(光センサーが黒いライン上にあるか判定) --> (右旋回を開始)
(光センサーが黒いライン上にあるか判定) --> (明るいと判定)
(明るいと判定) --> (左旋回を開始)
(右旋回を開始) --> (ラインの右境界線上を進む)
(左旋回を開始) --> (ラインの右境界線上を進む)
User --> (電源SWを切る)
(電源SWを切る) --> (システム停止)
}

@enduml