@startuml アクティ
|販売代理店|
|営業部門|
|製造部門|


|販売代理店|
start
:発注;
|販売代理店|

|営業部門|
:受注;
:在庫確認;
if() is(在庫有り)then
:;
note right
    作図の都合上,
    ダミーの
    アクティブ
    を記述
end note
|営業部門|
|製造部門|
else (在庫なし)
:製造;
endif
|営業部門|
:発送;
|販売代理店|
:検収/支払い;
|販売代理店|
|営業部門|
:入金確認;
|営業部門|
stop
@enduml


