@startuml
left to right direction
class 利用者{
 - 名前: Aさん
 - 住所
 - 電話番号
}

class ホテル{
  - 部屋  
}

class 部屋{
  - タイプ: シングル
  - 価格: 11,000円
  - キャンペーン価格: 9,000円
}

class 予約{
    - チェックイン日: 5月3日
    - 滞在期間: 2泊
    - 値段: 18,000円
}

ホテル " 1 " o-- "*" 部屋
利用者--> 予約:予約
ホテル" 1 "--"*"利用者:会員登録
予約-->部屋:予約
301号室 -- 部屋:301号室
303号室 -- 部屋:303号室
@enduml