@startuml
hide footbox
actor 受注係 as taker
participant "注文登録画面" as tyuumon
participant "商品" as merchandise
participant "注文" as order

activate taker
taker -> tyuumon


activate tyuumon
tyuumon -> merchandise:商品情報の確認（）

activate merchandise
merchandise --> tyuumon:商品情報の取得():情報を返す
tyuumon -> tyuumon:商品情報の表示

activate tyuumon
deactivate tyuumon


deactivate tyuumon
deactivate merchandise

 
taker -> tyuumon
activate tyuumon
tyuumon -> order:商品登録():注文オブジェクトを生成 <<include>>

activate order

deactivate tyuumon
@enduml