@startuml
hide footbox
actor 受注係 as taker
participant "注文登録画面" as screen
participant "商品" as merchandise
participant "注文" as order

activate taker
taker -> screen


activate screen
screen -> merchandise:商品情報の確認（）

activate merchandise
merchandise --> screen:商品情報の取得():情報を返す
screen -> screen:商品情報の表示

activate screen
deactivate screen


deactivate screen
deactivate merchandise

 
taker -> screen
activate screen
screen -> order:商品登録():注文オブジェクトを生成 <<include>>

activate order

deactivate screen
@enduml