@startuml ユースケース図
[*] -right-> 電源SWを入れる :システムの起動
state c <<choice>>
state c <<choice>>
電源SWを入れる -down-> c
c --> 左モーターon : ライン上に光センサーがある
c -down-> 右モーターon : ラインを外れる
右モーターon --> 右境界線上を進む
左モーターon --> 右境界線上を進む
右境界線上を進む --> 電源SWを切る
電源SWを切る -->[*] :システムの停止

