@startuml
hide footbox
actor 受注係 as taker
participant "注文登録画面" as Order registration screen
participant "商品" as merchandise
participant "注文" as order

activate taker
taker -> Order registration screen


activate Order registration screen
Order registration screen -> merchandise:商品情報の確認（）

activate merchandise
merchandise --> Order registration screen:商品情報の取得():情報を返す
Order registration screen -> Order registration screen:商品情報の表示

activate Order registration screen
deactivate Order registration screen


deactivate Order registration screen
deactivate merchandise

 
taker -> Order registration screen
activate Order registration screen
Order registration screen -> order:商品登録():注文オブジェクトを生成 <<include>>

activate order

deactivate Order registration screen
@enduml